type: unet
kwargs:
  down_block_types: [CrossAttnDownBlockSpatioTemporal, DownBlockSpatioTemporal]
  up_block_types: [UpBlockSpatioTemporal, CrossAttnUpBlockSpatioTemporal]
  block_out_channels: [32, 64]
  num_attention_heads: [2, 4]
  cross_attention_dim: 2