defaults:
  - _self_ # First takes priority so any properties redefined here take precedence
  - paths: ibme_cluster # Simply override in cli call


## GLOBAL EVAL SETTINGS
tasks: ['gen_latents', 'latents_to_videos', 'compute_metrics']

real_data_path: ${paths.data_path}/CAMUS_Processed_Frames
output_dir: ${run_dir}/evaluation

run_dir: ${paths.train_output_path}/hydra_outputs/2025-09-26/09-07-39
ckpt_name: last.ckpt

test_n_missing_frames: [max, 0.75, 0.5, 0.25]  # Proportion of frames to mask


## GENERATE LATENTS i.e. Inference parameters
inference_schemes:
  ef_histogram_matching:
    plan_path: ${paths.project_path}/evaluation/eval_plans/ef_histogram_matching_plan.csv  # Path to CSV file with generation plan
    batch_size: 16
    
  ef_samples_in_range:
    ef_gen_range: [0.1, 0.8]  # Range of ef_gen values to sample from uniformly
    n_ef_samples: 4  # Number of ef_gen samples per video in ef_gen_range

  frame_upsampling:
    batch_size: 16

model_sample_kwargs:
  guidance_scale: 1  # Classifier-free guidance scale; set to 1.0 for no guidance


## LATENT-TO-VIDEO PARAMETERS
repo_id: HReynaud/EchoFlow
types: [videowise]  # output types e.g., 'videowise' or 'framewise' or both
fps_metadata_csv: ${paths.data_path}/CAMUS_Latents_{vae_res}/metadata.csv # CSV with video_name and FPS column to override default FPS
queries:
  ef_histogram_matching:
    generation_nmfmax_bin0: 'n_missing_frames == "max" and target_ef_bin == 0'
    generation_nmfmax_bin1: 'n_missing_frames == "max" and target_ef_bin == 1'
    generation_nmfmax_bin2: 'n_missing_frames == "max" and target_ef_bin == 2'
    generation_nmfmax_bin3: 'n_missing_frames == "max" and target_ef_bin == 3'
    generation_nmfmax_bin4: 'n_missing_frames == "max" and target_ef_bin == 4'
    generation_nmf75p_bin0: 'n_missing_frames == "75p" and target_ef_bin == 0'
    generation_nmf75p_bin1: 'n_missing_frames == "75p" and target_ef_bin == 1'
    generation_nmf75p_bin2: 'n_missing_frames == "75p" and target_ef_bin == 2'
    generation_nmf75p_bin3: 'n_missing_frames == "75p" and target_ef_bin == 3'
    generation_nmf75p_bin4: 'n_missing_frames == "75p" and target_ef_bin == 4'
    generation_nmf50p_bin0: 'n_missing_frames == "50p" and target_ef_bin == 0'
    generation_nmf50p_bin1: 'n_missing_frames == "50p" and target_ef_bin == 1'
    generation_nmf50p_bin2: 'n_missing_frames == "50p" and target_ef_bin == 2'
    generation_nmf50p_bin3: 'n_missing_frames == "50p" and target_ef_bin == 3'
    generation_nmf50p_bin4: 'n_missing_frames == "50p" and target_ef_bin == 4'
    generation_nmf25p_bin0: 'n_missing_frames == "25p" and target_ef_bin == 0'
    generation_nmf25p_bin1: 'n_missing_frames == "25p" and target_ef_bin == 1'
    generation_nmf25p_bin2: 'n_missing_frames == "25p" and target_ef_bin == 2'
    generation_nmf25p_bin3: 'n_missing_frames == "25p" and target_ef_bin == 3'
    generation_nmf25p_bin4: 'n_missing_frames == "25p" and target_ef_bin == 4'

  ef_samples_in_range:
    reconstruction_nmfmax: 'rec_or_gen == "rec" and n_missing_frames == "max"'
    reconstruction_nmf75p: 'rec_or_gen == "rec" and n_missing_frames == "75p"'
    reconstruction_nmf50p: 'rec_or_gen == "rec" and n_missing_frames == "50p"'
    reconstruction_nmf25p: 'rec_or_gen == "rec" and n_missing_frames == "25p"'
    generation_nmfmax: 'rec_or_gen == "gen" and n_missing_frames == "max"'
    generation_nmf75p: 'rec_or_gen == "gen" and n_missing_frames == "75p"'
    generation_nmf50p: 'rec_or_gen == "gen" and n_missing_frames == "50p"'
    generation_nmf25p: 'rec_or_gen == "gen" and n_missing_frames == "25p"'

  frame_upsampling:
    reconstruction_nmf50p: 'rec_or_gen == "rec" and n_missing_frames == "50p"'
    reconstruction_nmf66p: 'rec_or_gen == "rec" and n_missing_frames == "66p"'
    reconstruction_nmf75p: 'rec_or_gen == "rec" and n_missing_frames == "75p"'

## COMPUTE METRICS
metrics:
  real_glob: ['*']            # glob pattern to match real videos
  fake_glob: ['*']            # glob pattern to match generated videos
  which: [ssim, psnr, lpips_vgg]  # metrics to compute
  stylegan_metrics: [fid50k_full, fvd2048_10f]
  confidence: 0.95           # confidence level for CIs
  #resize: [112, 112]         # optional resize (H, W); set to null to keep native


hydra:
  run:
    dir: ${output_dir}/eval_cfgs/${now:%Y-%m-%d}/${now:%H-%M-%S}