defaults:
  - _self_ # First takes priority so any properties redefined here take precedence
  - paths: ibme_cluster # Simply override in cli call

tasks: ['gen_latents']

run_dir: ${paths.train_output_path}/hydra_outputs/2025-10-12/21-13-24
ckpt_name: last.ckpt

output_dir: ${run_dir}/evaluation
# Debugging
debugging: true
dataset_kwargs:
  n_sample_videos: 20

## GENERATE LATENTS i.e. Inference parameters
inference_schemes:
  ef_histogram_matching:
    plan_path: ${paths.project_path}/evaluation/eval_plans/ef_histogram_matching_plan.csv  # Path to CSV file with generation plan
    batch_size: 2
    
  ef_samples_in_range:
    ef_gen_range: [0.1, 0.8]  # Range of ef_gen values to sample from uniformly
    n_ef_samples: 4  # Number of ef_gen samples per video in ef_gen_range

model_sample_kwargs:
  guidance_scale: 5  # Classifier-free guidance scale; set to 1.0 for no guidance

