defaults:
  - _self_ # First takes priority so any properties redefined here take precedence
  - paths: ibme_cluster # Simply override in cli call

tasks: ['compute_metrics']
run_dir: ${paths.train_output_path}/hydra_outputs/2025-10-12/21-13-24


## COMPUTE METRICS
output_dir: ${run_dir}/evaluation
time_and_date: '2025-10-03/20-37-30'  # Subdirectory under latents_dir to evaluate
videos_root: ${run_dir}/evaluation/decoded_videos/${time_and_date} #null # Directory containing decoded videos; if null, will use output of latents_to_videos step


metrics:
  inference_roots:
    ef_histogram_matching: 
      generation_nmfmax_bin0: ${videos_root}/ef_histogram_matching/generation/nmfmax/bin0
      generation_nmfmax_bin1: ${videos_root}/ef_histogram_matching/generation/nmfmax/bin1
      generation_nmfmax_bin2: ${videos_root}/ef_histogram_matching/generation/nmfmax/bin2
      generation_nmfmax_bin3: ${videos_root}/ef_histogram_matching/generation/nmfmax/bin3
      generation_nmfmax_bin4: ${videos_root}/ef_histogram_matching/generation/nmfmax/bin4
      generation_nmf75p_bin0: ${videos_root}/ef_histogram_matching/generation/nmf75p/bin0
      generation_nmf75p_bin1: ${videos_root}/ef_histogram_matching/generation/nmf75p/bin1
      generation_nmf75p_bin2: ${videos_root}/ef_histogram_matching/generation/nmf75p/bin2
      generation_nmf75p_bin3: ${videos_root}/ef_histogram_matching/generation/nmf75p/bin3
      generation_nmf75p_bin4: ${videos_root}/ef_histogram_matching/generation/nmf75p/bin4
      generation_nmf50p_bin0: ${videos_root}/ef_histogram_matching/generation/nmf50p/bin0
      generation_nmf50p_bin1: ${videos_root}/ef_histogram_matching/generation/nmf50p/bin1
      generation_nmf50p_bin2: ${videos_root}/ef_histogram_matching/generation/nmf50p/bin2
      generation_nmf50p_bin3: ${videos_root}/ef_histogram_matching/generation/nmf50p/bin3
      generation_nmf50p_bin4: ${videos_root}/ef_histogram_matching/generation/nmf50p/bin4
      generation_nmf25p_bin0: ${videos_root}/ef_histogram_matching/generation/nmf25p/bin0
      generation_nmf25p_bin1: ${videos_root}/ef_histogram_matching/generation/nmf25p/bin1
      generation_nmf25p_bin2: ${videos_root}/ef_histogram_matching/generation/nmf25p/bin2
      generation_nmf25p_bin3: ${videos_root}/ef_histogram_matching/generation/nmf25p/bin3
      generation_nmf25p_bin4: ${videos_root}/ef_histogram_matching/generation/nmf25p/bin4

    ef_samples_in_range:
      reconstruction_nmfmax: ${videos_root}/ef_samples_in_range/reconstruction/nmfmax
      reconstruction_nmf75p: ${videos_root}/ef_samples_in_range/reconstruction/nmf75p
      reconstruction_nmf50p: ${videos_root}/ef_samples_in_range/reconstruction/nmf50p
      reconstruction_nmf25p: ${videos_root}/ef_samples_in_range/reconstruction/nmf25p
      generation_nmfmax: ${videos_root}/ef_samples_in_range/generation/nmfmax
      generation_nmf75p: ${videos_root}/ef_samples_in_range/generation/nmf75p
      generation_nmf50p: ${videos_root}/ef_samples_in_range/generation/nmf50p
      generation_nmf25p: ${videos_root}/ef_samples_in_range/generation/nmf25p

  real_glob: ['*']            # glob pattern to match real videos
  fake_glob: ['*']            # glob pattern to match generated videos
  pairwise_metrics: [ssim, psnr, lpips_vgg, mae, mse]  # metrics to compute
  stylegan_metrics: [fid50k_full, fvd2048_10f]
  confidence: 0.95           # confidence level for CIs