project_path: /users/spet4299/code/TEE/flow-matching/go-with-the-flow
data_path: /users/spet4299/code/TEE/flow-matching/go-with-the-flow/data
train_output_path: ${oc.env:DATA}/flow-matching/go-with-the-flow/outputs