seed: 42

dataset:
  data_path: "./data/CAMUS_Processed"
  metadata_csv: "camus_ef_results.csv"
  deactivate_cache: True
  image_size: 48 #112
  channels: 3
  target_frames: 32
  preload_data: False
  data_mean: 0.187211
  data_std: 0.220990


dataloader:
  batch_size: 2 #16
  num_workers: 32

trainer:
  max_epochs: 100
  lr: 1e-5
  fc_lr: 1e-4
  weight_decay: 7e-5

wandb:
  project: "ef_regression"
  entity: "engemmanuel"

checkpoint:
  path: "./outputs/ef_regression"
